"""Generates and manages ProjectArchitecture.md template and context."""

import datetime
from pathlib import Path
from metzuda.models.config import MetzudaConfig

ARCHITECTURE_FILE = Path("ProjectArchitecture.md")
TEMPLATE = """# Project Architecture

> **Note:** This file will be used for context to help and improve the AI scan.

<!-- Auto-generated by Metzuda on {date}. Edit to improve AI security analysis. -->
<!-- The more context you provide, the better Metzuda can find security issues. -->

## Tech Stack
- Language: {language}
- Framework: [fill in: Express / FastAPI / Spring Boot / etc.]
- Database: [fill in: MySQL / PostgreSQL / MongoDB / etc.]
- ORM / Query Builder: [fill in: Prisma / TypeORM / SQLAlchemy / etc.]
- Authentication: [fill in: JWT / Sessions / OAuth2 / etc.]
- Deploy: [fill in: Railway / Vercel / AWS / Docker / etc.]

## Authentication Rules
<!-- IMPORTANT: Metzuda uses these rules to detect auth violations -->
- All routes except /auth/* and /public/* require authentication
- User identity must come from the verified token, never from request parameters
- Resource ownership must be checked before returning any user-specific data
- [Add your specific auth rules here]

## Data Access Rules
- [Describe how your app accesses the database]
- [e.g.: All queries use Prisma ORM — no raw SQL]
- [e.g.: Users can only read/write their own records unless role is ADMIN]

## API Patterns
- [Describe your API conventions]
- [e.g.: RESTful, all IDs are UUIDs, never expose sequential integers]
- [e.g.: Responses never include password or token fields]

## Project Structure (auto-scanned)
{directory_tree}

## Additional Security Context
<!-- Any other security rules specific to your project -->
<!-- Examples: -->
<!-- - Payment routes require 2FA verification -->
<!-- - Admin routes are only accessible from internal network -->
"""


def create_architecture_file(config: MetzudaConfig, root: Path = Path(".")) -> Path:
    """
    Creates ProjectArchitecture.md with a pre-filled template.
    Includes auto-scanned directory structure.
    """
    tree = _build_directory_tree(root, config)
    content = TEMPLATE.format(
        date=datetime.date.today().isoformat(),
        language=config.language,
        directory_tree=tree,
    )

    target = root / "ProjectArchitecture.md" if root != Path(".") else ARCHITECTURE_FILE
    target.write_text(content, encoding="utf-8")
    return target


def _build_directory_tree(root: Path, config: MetzudaConfig, max_depth: int = 3) -> str:
    """
    Generates a markdown code block with directory tree.
    Respects ignore paths from config.
    Max depth 3 to keep it readable.
    """
    root = root.resolve()
    lines = ["```", f"{root.name}/"]

    def _recurse(path: Path, prefix: str, depth: int) -> None:
        if depth > max_depth:
            return
        try:
            entries = sorted(path.iterdir(), key=lambda e: (e.is_file(), e.name))
        except PermissionError:
            return

        valid_entries = []
        for entry in entries:
            try:
                rel_str = str(entry.relative_to(root))
            except ValueError:
                rel_str = entry.name

            if any(
                p.rstrip("/") == rel_str or rel_str.startswith(p.rstrip("/") + "/") or p.rstrip("/") == entry.name
                for p in config.ignore_paths
            ):
                continue
            if entry.name.startswith("."):
                continue
            valid_entries.append(entry)

        for entry in valid_entries:
            connector = "└── " if entry == valid_entries[-1] else "├── "
            lines.append(f"{prefix}{connector}{entry.name}")

            if entry.is_dir() and depth < max_depth:
                extension = "    " if entry == valid_entries[-1] else "│   "
                _recurse(entry, prefix + extension, depth + 1)

    _recurse(root, "", 1)
    lines.append("```")
    return "\n".join(lines)


def get_architecture_context(state: dict, root: Path = Path(".")) -> tuple[str | None, bool]:
    """
    Returns (content, changed) where changed=True if file hash differs from state.
    Returns (None, False) if file doesn't exist.
    """
    from metzuda.infra.state_manager import file_hash

    arch_file = root / "ProjectArchitecture.md" if root != Path(".") else ARCHITECTURE_FILE

    if not arch_file.exists():
        return None, False

    content = arch_file.read_text(encoding="utf-8")
    current_hash = file_hash(arch_file)
    saved_hash = state.get("architecture_hash")
    changed = current_hash != saved_hash

    return content, changed
